<?php

/**
 * BasePrestaDomain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $presta_id
 * @property integer $domain_id
 * 
 * @method integer      getPrestaId()  Returns the current record's "presta_id" value
 * @method integer      getDomainId()  Returns the current record's "domain_id" value
 * @method PrestaDomain setPrestaId()  Sets the current record's "presta_id" value
 * @method PrestaDomain setDomainId()  Sets the current record's "domain_id" value
 * 
 * @package    ijani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePrestaDomain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('presta_domain');
        $this->hasColumn('presta_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('domain_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}