<?php

/**
 * BaseUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $first_name
 * @property string $last_name
 * @property text $address
 * @property string $latitude
 * @property string $longitude
 * 
 * @method string getFirstName()  Returns the current record's "first_name" value
 * @method string getLastName()   Returns the current record's "last_name" value
 * @method text   getAddress()    Returns the current record's "address" value
 * @method string getLatitude()   Returns the current record's "latitude" value
 * @method string getLongitude()  Returns the current record's "longitude" value
 * @method User   setFirstName()  Sets the current record's "first_name" value
 * @method User   setLastName()   Sets the current record's "last_name" value
 * @method User   setAddress()    Sets the current record's "address" value
 * @method User   setLatitude()   Sets the current record's "latitude" value
 * @method User   setLongitude()  Sets the current record's "longitude" value
 * 
 * @package    ijani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseUser extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user');
        $this->hasColumn('first_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('last_name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('address', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('latitude', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('longitude', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}