<?php

/**
 * BaseDomain
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $Prestas
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getPrestas() Returns the current record's "Prestas" collection
 * @method Domain              setName()    Sets the current record's "name" value
 * @method Domain              setPrestas() Sets the current record's "Prestas" collection
 * 
 * @package    ijani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDomain extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('domain');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Presta as Prestas', array(
             'refClass' => 'PrestaDomain',
             'local' => 'domain_id',
             'foreign' => 'presta_id'));
    }
}