<?php

/**
 * BaseTown
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $state_id
 * @property State $State
 * @property Doctrine_Collection $Locality
 * 
 * @method string              getName()     Returns the current record's "name" value
 * @method integer             getStateId()  Returns the current record's "state_id" value
 * @method State               getState()    Returns the current record's "State" value
 * @method Doctrine_Collection getLocality() Returns the current record's "Locality" collection
 * @method Town                setName()     Sets the current record's "name" value
 * @method Town                setStateId()  Sets the current record's "state_id" value
 * @method Town                setState()    Sets the current record's "State" value
 * @method Town                setLocality() Sets the current record's "Locality" collection
 * 
 * @package    ijani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseTown extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('town');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('state_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('State', array(
             'local' => 'state_id',
             'foreign' => 'id'));

        $this->hasMany('Locality', array(
             'local' => 'id',
             'foreign' => 'town_id'));
    }
}