<?php

/**
 * BasePresta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $presentation
 * @property string $address
 * @property string $latitude
 * @property string $longitude
 * @property string $tel
 * @property string $mobile
 * @property string $fax
 * @property integer $locality_id
 * @property float $rating
 * @property string $reperes
 * @property Locality $Locality
 * @property Doctrine_Collection $Domaines
 * 
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getPresentation() Returns the current record's "presentation" value
 * @method string              getAddress()      Returns the current record's "address" value
 * @method string              getLatitude()     Returns the current record's "latitude" value
 * @method string              getLongitude()    Returns the current record's "longitude" value
 * @method string              getTel()          Returns the current record's "tel" value
 * @method string              getMobile()       Returns the current record's "mobile" value
 * @method string              getFax()          Returns the current record's "fax" value
 * @method integer             getLocalityId()   Returns the current record's "locality_id" value
 * @method float               getRating()       Returns the current record's "rating" value
 * @method string              getReperes()      Returns the current record's "reperes" value
 * @method Locality            getLocality()     Returns the current record's "Locality" value
 * @method Doctrine_Collection getDomaines()     Returns the current record's "Domaines" collection
 * @method Presta              setName()         Sets the current record's "name" value
 * @method Presta              setPresentation() Sets the current record's "presentation" value
 * @method Presta              setAddress()      Sets the current record's "address" value
 * @method Presta              setLatitude()     Sets the current record's "latitude" value
 * @method Presta              setLongitude()    Sets the current record's "longitude" value
 * @method Presta              setTel()          Sets the current record's "tel" value
 * @method Presta              setMobile()       Sets the current record's "mobile" value
 * @method Presta              setFax()          Sets the current record's "fax" value
 * @method Presta              setLocalityId()   Sets the current record's "locality_id" value
 * @method Presta              setRating()       Sets the current record's "rating" value
 * @method Presta              setReperes()      Sets the current record's "reperes" value
 * @method Presta              setLocality()     Sets the current record's "Locality" value
 * @method Presta              setDomaines()     Sets the current record's "Domaines" collection
 * 
 * @package    ijani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasePresta extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('presta');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('presentation', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('latitude', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('longitude', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('tel', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('mobile', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('fax', 'string', 20, array(
             'type' => 'string',
             'length' => 20,
             ));
        $this->hasColumn('locality_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rating', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('reperes', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Locality', array(
             'local' => 'locality_id',
             'foreign' => 'id'));

        $this->hasMany('Domain as Domaines', array(
             'refClass' => 'PrestaDomain',
             'local' => 'presta_id',
             'foreign' => 'domain_id'));

        $taggable0 = new Taggable();
        $commentable0 = new Doctrine_Template_Commentable();
        $this->actAs($taggable0);
        $this->actAs($commentable0);
    }
}