<?php

/**
 * BaseLocality
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property integer $town_id
 * @property Town $Town
 * @property Doctrine_Collection $Presta
 * 
 * @method string              getName()    Returns the current record's "name" value
 * @method integer             getTownId()  Returns the current record's "town_id" value
 * @method Town                getTown()    Returns the current record's "Town" value
 * @method Doctrine_Collection getPresta()  Returns the current record's "Presta" collection
 * @method Locality            setName()    Sets the current record's "name" value
 * @method Locality            setTownId()  Sets the current record's "town_id" value
 * @method Locality            setTown()    Sets the current record's "Town" value
 * @method Locality            setPresta()  Sets the current record's "Presta" collection
 * 
 * @package    ijani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseLocality extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('locality');
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('town_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Town', array(
             'local' => 'town_id',
             'foreign' => 'id'));

        $this->hasMany('Presta', array(
             'local' => 'id',
             'foreign' => 'locality_id'));
    }
}