<?php

/**
 * LocalityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LocalityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LocalityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Locality');
    }

    public function getByTownId($town_id) {
      return $this->createQuery('l')
              ->where('l.town_id = ?', $town_id)
              ->orderBy('l.name ASC')
              ->execute();
    }
}