<?php

/**
 * PrestaDomainTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrestaDomainTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrestaDomainTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PrestaDomain');
    }
}