<?php

/**
 * Presta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ijani
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
class Presta extends BasePresta
{
  public function getTown() {
    return $this->getLocality()->getTown();
  }
}
