<?php

/**
 * PrestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrestaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Presta');
    }

    public function getByDomainAndLocality($domain_id, $locality_id) {
      return $this->createQuery("p")
              ->innerJoin("p.PrestaDomain pd")
              ->where("p.locality_id = ?", $locality_id)
              ->andWhere("pd.domain_id = ?", $domain_id)
              ->orderBy("p.name")
              ->execute();
    }
}