<?php

/**
 * PrestaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PrestaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PrestaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Presta');
    }

    public function getByDomainAndLocality($domain_id, $locality_id) {
      return $this->createQuery("p")
              ->innerJoin("p.PrestaDomain pd")
              ->where("p.locality_id = ?", $locality_id)
              ->andWhere("pd.domain_id = ?", $domain_id)
              ->orderBy("p.name")
              ->execute();
    }

    public function getByDomainAndTown($domain_id, $town_id) {
      return $this->createQuery("p")
              ->innerJoin("p.PrestaDomain pd")
              ->innerJoin("p.Locality l")
              ->where("pd.domain_id = ?", $domain_id)
              ->andWhere("l.town_id = ?", $town_id)
              ->orderBy("p.name")
              ->execute();
    }

    public function getByDomainAndState($domain_id, $state_id) {
      return $this->createQuery("p")
              ->innerJoin("p.PrestaDomain pd")
              ->innerJoin("p.Locality l")
              ->innerJoin("l.Town t")
              ->where("pd.domain_id = ?", $domain_id)
              ->andWhere("t.state_id = ?", $state_id)
              ->orderBy("p.name")
              ->execute();
    }

    public function getByLocality($locality_id) {
      return $this->createQuery("p")
              ->where("p.locality_id = ?", $locality_id)
              ->orderBy("p.name")
              ->execute();
    }

    public function getByTown($town_id) {
      return $this->createQuery("p")
              ->innerJoin("p.Locality l")
              ->where("l.town_id = ?", $town_id)
              ->orderBy("p.name")
              ->execute();
    }

    public function getByState($state_id) {
      return $this->createQuery("p")
              ->innerJoin("p.Locality l")
              ->innerJoin("l.Town t")
              ->where("t.state_id = ?", $state_id)
              ->orderBy("p.name")
              ->execute();
    }
}