# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:
    - blueprint/screen.css
    - blueprint/plugins/fancy-type/screen.css
    - /js/jquery.ui.stars/jquery.ui.stars.css

  javascripts:
    - jquery-1.5.1.js
    - jquery-ui-1.8.11.custom.min.js
    - /js/jquery.ui.stars/jquery.ui.stars.min.js
    - effects.js

  has_layout:     true
  layout:         layout
