<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version19 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->removeColumn('domain', 'nom');
    }

    public function down()
    {
        $this->addColumn('domain', 'nom', 'string', '50', array(
             ));
    }
}