<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version21 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createForeignKey('presta', 'presta_locality_id_locality_id', array(
             'name' => 'presta_locality_id_locality_id',
             'local' => 'locality_id',
             'foreign' => 'id',
             'foreignTable' => 'locality',
             ));
        $this->addIndex('presta', 'presta_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
    }

    public function down()
    {
        $this->dropForeignKey('presta', 'presta_locality_id_locality_id');
        $this->removeIndex('presta', 'presta_locality_id', array(
             'fields' => 
             array(
              0 => 'locality_id',
             ),
             ));
    }
}