<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Addprestadomain extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('presta_domain', array(
             'presta_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             'domain_id' => 
             array(
              'type' => 'integer',
              'primary' => true,
              'length' => 8,
             ),
             ), array(
             'indexes' => 
             array(
             ),
             'primary' => 
             array(
              0 => 'presta_id',
              1 => 'domain_id',
             ),
             'charset' => 'UTF8',
             ));
    }

    public function down()
    {
        $this->dropTable('presta_domain');
    }
}