<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version18 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('domain', 'name', 'string', '50', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('domain', 'name');
    }
}