<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version22 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('tag', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'is_triple' => 
             array(
              'type' => 'boolean',
              'length' => '25',
             ),
             'triple_namespace' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'triple_key' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             'triple_value' => 
             array(
              'type' => 'string',
              'length' => '100',
             ),
             ), array(
             'indexes' => 
             array(
              'name' => 
              array(
              'fields' => 
              array(
               0 => 'name',
              ),
              ),
              'triple1' => 
              array(
              'fields' => 
              array(
               0 => 'triple_namespace',
              ),
              ),
              'triple2' => 
              array(
              'fields' => 
              array(
               0 => 'triple_key',
              ),
              ),
              'triple3' => 
              array(
              'fields' => 
              array(
               0 => 'triple_value',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
        $this->createTable('tagging', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'tag_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'taggable_model' => 
             array(
              'type' => 'string',
              'length' => '30',
             ),
             'taggable_id' => 
             array(
              'type' => 'integer',
              'length' => '8',
             ),
             ), array(
             'indexes' => 
             array(
              'tag' => 
              array(
              'fields' => 
              array(
               0 => 'tag_id',
              ),
              ),
              'taggable' => 
              array(
              'fields' => 
              array(
               0 => 'taggable_model',
               1 => 'taggable_id',
              ),
              ),
             ),
             'primary' => 
             array(
              0 => 'id',
             ),
             ));
    }

    public function down()
    {
        $this->dropTable('tag');
        $this->dropTable('tagging');
    }
}