<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version25 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('presta', 'rating', 'float', '', array(
             ));
        $this->addColumn('presta', 'reperes', 'string', '100', array(
             ));
    }

    public function down()
    {
        $this->removeColumn('presta', 'rating');
        $this->removeColumn('presta', 'reperes');
    }
}